ci:
  submodules: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Common errors
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer

      # Git style
      - id: check-merge-conflict

        # Security
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
#      - id: terraform_docs
#        args:
#          - '--args=--lockfile=false'
      - id: terraform_tflint
        files: ^examples/example_.+/ # only scan `examples/example_*`
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          #- '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          #- '--args=--only=terraform_documented_outputs'
          #- '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
      - id: terraform_validate
        files: ^examples/example_.+/ # only scan `examples/example_*`
      - id: terraform_tfsec
        files: ^examples/ # only scan `examples`
        args:
          - --args=--config-file=__GIT_WORKING_DIR__/tfsec.yaml
          - --args=--concise-output
