name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'gh-pages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: gh-pages/package-lock.json
      - name: Create vitepress site
        run: |
          cd gh-pages
          npm i
          npm run docs:build
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages/docs/.vitepress/dist
